##############
## DATABASE ##
##############
spring:
  flyway:
    locations: classpath:db/migration/test
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:account_backend;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /