name: Route Metrics Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle (using flags)
        run: gradle -b infrastructure/build.gradle -DprojectDir=infrastructure build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: infrastructure/build/libs/route-metrics-backend.jar

  deploy-docker-hub:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-artifacts
          path: infrastructure/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: torhugo/route-metrics:latest

  deploy-oracle-vps:
    runs-on: ubuntu-latest

    needs: deploy-docker-hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Oracle VPS, Pull Docker images, Restart containers
        uses: webfactory/ssh-agent@v0.5.3
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "cd ~/ && \
          sudo docker-compose pull && \
          sudo docker-compose restart"
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}