name: Route Metrics Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Start RabbitMQ container
        uses: docker/setup-qemu-action@v2
        with:
          dockerfile: rabbitmq:latest

      - name: Build with Gradle (using flags)
        run: gradle -b infrastructure/build.gradle -DprojectDir=infrastructure build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: torhugo/route-metrics:latest