name: Route Metrics Pipeline

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'

jobs:

  deploy-build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5672:5672

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Build with Gradle (using flags)
        run: gradle -b infrastructure/build.gradle -DprojectDir=infrastructure build

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: infrastructure/build/libs/route-metrics-backend.jar

  deploy-tests:
    runs-on: ubuntu-latest

    needs: deploy-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Run domain tests.
        run: gradle -b domain/build.gradle -DprojectDir=domain build

  deploy-docker-hub:
    runs-on: ubuntu-latest

    needs: deploy-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: app-artifacts
          path: infrastructure/build/libs/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: torhugo/route-metrics:latest

  deploy-oracle-vps:
    runs-on: ubuntu-latest

    needs: deploy-docker-hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Oracle VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ./script.sh

  discord-notification:
    runs-on: ubuntu-latest

    needs: deploy-oracle-vps

    steps:
    - name: Discord Notification
      uses: sarisia/actions-status-discord@v1.9.0
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "Backend Route Metrics"
        description: "Build and Deploy to Server"
        username: GitHub Actions